Repository isaqb-org/curriculum-foundation, pull requests merged in 2022-10, with the labels that each got.

#280 fixed #271 for LG 2-5 (explain abbreviations)
  docs/02-design/LZ-2-05.adoc
Labels: enhancement

#293 #250, LG 2-5 add the term clean-architecture
  docs/02-design/LZ-2-05.adoc
  docs/09-references/00-references.adoc
Labels: V2023

#294 #282, simplify introductory sentence
  docs/02-design/LZ-2-06.adoc
Labels: V2023

#304 02-Design Terms: Removed "functional and technical architectures"
  docs/02-design/01-design-duration-terms.adoc
Labels: V2023

#305 #303 fix German translation of "domain-related"
  docs/02-design/LZ-2-02.adoc
Labels: V2023

#292 #270 add energy efficiency to appropriate LGs
  docs/01-basics/LZ-1-02.adoc
  docs/02-design/LZ-2-04.adoc
  docs/02-design/LZ-2-08.adoc
Labels: learning content, enhancement, V2023
