Repository isaqb-org/curriculum-foundation, pull requests merged in 2022-12, with the labels that each got.

#322 LG 2-3 change title and intro sentences (fixing #320)
  docs/02-design/LZ-2-03.adoc
Labels: V2023

#323 LG 2-3, addressed #321, refactored subgoals, updated terminology
  docs/02-design/LZ-2-03.adoc
Labels: enhancement, V2023

#325 #319 lg 3 2 translation wording
  .gitignore
  docs/03-documentation/LZ-3-02.adoc
Labels: trivial, V2023

#327 #317 update references to iso 25010
  .gitignore
  docs/04-quality/LZ-4-1.adoc
  docs/09-references/00-references.adoc
  document.version
Labels: enhancement, V2023

#330 Add changes from template
  .github/workflows/build_main.yml
  .github/workflows/build_pr.yml
  .github/workflows/build_releasecandidate.yml
  .gitmodules
  CHANGELOG.md
  build.gradle
  docs/curriculum-foundation.adoc
  docs/images/isaqb-logo.jpg
  docs/isaqb-logo.jpg
  document.validity
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement, V2023

#326 #312 lg 3 2 merge with lg 3 9
  docs/03-documentation/00-documentation.adoc
  docs/03-documentation/LZ-3-02.adoc
  docs/03-documentation/LZ-3-09.adoc
  docs/03-documentation/LZ-3-10.adoc
Labels: learning content, enhancement, V2023

#333 #332 fix typos
  docs/00-preamble/01-what-to-expect.adoc
  docs/00-preamble/05-exam-relevance-levels.adoc
  docs/01-basics/LZ-1-04.adoc
  docs/01-basics/LZ-1-07.adoc
  docs/01-basics/LZ-1-08.adoc
  docs/01-basics/LZ-1-10.adoc
  docs/02-design/00-design.adoc
  docs/02-design/LZ-2-02.adoc
  docs/02-design/LZ-2-06.adoc
  docs/02-design/LZ-2-07.adoc
  docs/02-design/LZ-2-10.adoc
Labels: bug, trivial, V2023

#334 #332 more trivial typos
  docs/02-design/LZ-2-04.adoc
  docs/02-design/LZ-2-05.adoc
  docs/02-design/LZ-2-06.adoc
  docs/09-references/00-references.adoc
Labels: trivial, V2023
