Repository isaqb-org/curriculum-foundation, pull requests merged in 2023-02, with the labels that each got.

#358 #351 lg 3 2 fix missing r2 in header
  docs/03-documentation/LZ-3-02.adoc
Labels: V2023

#359 fix #349, fix formating of italics
  docs/01-basics/LZ-1-04.adoc
Labels: bug

#355 Fix typo in LG 1-2: remove duplicate "the"
  docs/01-basics/LZ-1-02.adoc
Labels: V2023

#360 add q42 reference
  docs/09-references/00-references.adoc
Labels: enhancement, V2023
