Repository isaqb-org/curriculum-foundation, pull requests merged in 2024-10, with the labels that each got.

#531 #443 migration guide
  CHANGELOG.md
  documentation/changelogs/readme-changelogs.md
Labels: V2025

#553 Remove Types of IT Systems from Relevant Terms, refs #538
  docs/01-basics/01-basics-duration-terms.adoc
Labels: V2025

#552 Specify Exam Relevance for LG 02-01
  docs/02-requirements/LZ-02-01.adoc
Labels: bug, V2025

#558 # 556 remove redundant backlink
  docs/01-basics/LZ-01-05.adoc
  documentation/decisions/002-Keep_old_LG_numbers_in_2025_curriculum_for_reference.md
Labels: bug, V2025, documentation

#560 #547, LG-04-03, added ERD and Peter Chen reference
  docs/04-documentation/LZ-04-03.adoc
  docs/09-references/00-references.adoc
Labels: enhancement, V2025

#559 #542, LG-02-01, also refering to #397: reduce relevance of short- and…
  docs/02-requirements/LZ-02-01.adoc
Labels: enhancement, examination

#555 #539, LG-01-03: slightly changed wording regarding to requirements
  docs/01-basics/LZ-01-03.adoc
Labels: in progress, enhancement

#554 #545 LG-02-03, rephrased intro sentence. Removed quotes.
  docs/02-requirements/LZ-02-03.adoc
Labels: enhancement, V2025

#563 moved the liskov-sentence from LG-03-07 to LG-03-04
  docs/03-design/LZ-03-04.adoc
  docs/03-design/LZ-03-07.adoc
Labels: enhancement, V2025

#566 add table footer so bottom line gets visually separated
  docs/00-preamble/04-structure-timing-didactics.adoc
Labels: V2025, documentation

#568 #550 views can be helpful
  docs/04-documentation/LG-04-05.adoc
Labels: enhancement, V2025

#571 Lg 01 06 add kleppman reference
  docs/01-basics/00-basic-concepts.adoc
  docs/01-basics/99-basics-references.adoc
  docs/01-basics/LG-01-01.adoc
  docs/01-basics/LG-01-06.adoc
Labels: V2025

#595 explained the reference section, add to readme
  README.adoc
  documentation/decisions/007-distinct-references-section-for-LGs.md
Labels: documentation

#614 #606-replaced Design-Decisions by Architecture Decisions
  docs/02-requirements/LG-02-02.adoc
  docs/03-design/01-design-duration-terms.adoc
  docs/03-design/LG-03-02.adoc
  docs/03-design/LG-03-05.adoc
  docs/04-documentation/01-documentation-duration-terms.adoc
  docs/04-documentation/LG-04-08.adoc
Labels: learning content, enhancement, V2025, examination

#573 #572 fixed timing proposals in section headings
  docs/02-requirements/01-requirements-duration-terms.adoc
  docs/03-design/01-design-duration-terms.adoc
  docs/05-evaluation/01-evaluation-duration-terms.adoc
Labels: V2025

#579 #535 create reference sections for l gs
  docs/01-basics/00-basic-concepts.adoc
  docs/02-requirements/00-requirements.adoc
  docs/02-requirements/99-requirements-references.adoc
  docs/02-requirements/LG-02-03.adoc
  docs/02-requirements/LG-02-04.adoc
  docs/03-design/00-design.adoc
  docs/03-design/99-design-references.adoc
  docs/03-design/LG-03-02.adoc
  docs/03-design/LG-03-04.adoc
  docs/03-design/LG-03-06.adoc
  docs/03-design/LG-03-07.adoc
  docs/03-design/LG-03-08.adoc
  docs/03-design/LG-03-09.adoc
  docs/03-design/LG-03-10.adoc
  docs/03-design/LG-03-11.adoc
  docs/03-design/LG-03-12.adoc
  docs/04-documentation/00-documentation.adoc
  docs/04-documentation/99-documentation-references.adoc
  docs/04-documentation/LG-04-01.adoc
  docs/04-documentation/LG-04-03.adoc
  docs/04-documentation/LG-04-04.adoc
  docs/04-documentation/LG-04-08.adoc
  docs/04-documentation/LG-04-09.adoc
  docs/05-evaluation/00-evaluation.adoc
  docs/05-evaluation/99-evaluation-references.adoc
  docs/05-evaluation/LG-05-01.adoc
  docs/05-evaluation/LG-05-02.adoc
  docs/06-examples/LG-06-01.adoc
  docs/06-examples/LG-06-02.adoc
Labels: enhancement, V2025, examination

#610 add Cloud, microservices, container, generative AI or LLMs
  docs/02-requirements/LG-02-02.adoc
Labels: enhancement, V2025

#616 #599-LG-03-01-achieve-or-improve-qualities
  docs/03-design/LG-03-01.adoc
Labels: learning content, V2025

#619 #570 understand instead of discuss
  docs/01-basics/LG-01-01.adoc
Labels: learning content, V2025

#620 #602-LG-05-01 clarify wording
  docs/05-evaluation/LG-05-01.adoc
Labels: learning content, enhancement, V2025

#574 LG-02-01 improve wording, re-order table
  docs/02-requirements/LG-02-01.adoc
Labels: enhancement, V2025

#626 #594 LG-03-04 re-introduced SOLID after lengthy discussion
  docs/03-design/LG-03-04.adoc
  docs/09-references/00-references.adoc
Labels: learning content, V2025

#628 added POLA as synonym for principle of least surprise
  docs/03-design/LG-03-04.adoc
Labels: enhancement, V2025

#627 #601 LG-03-09 explain relevance of design patterns
  docs/03-design/LG-03-09.adoc
Labels: enhancement, V2025

#598 #578-add-DRY-to-LG-03-04
  docs/03-design/LG-03-04.adoc
Labels: learning content, enhancement, V2025, examination

#629 #582 add dependency injection to LG-03-06 and cross-reference it
  docs/03-design/LG-03-06.adoc
  docs/03-design/LG-03-08.adoc
Labels: enhancement, V2025

#636 Issue #575 - Remove FMC
  docs/04-documentation/LG-04-09.adoc
  docs/09-references/00-references.adoc
Labels: V2025

#646 Removed line that was inadvertently left in by the last change.
  docs/03-design/LG-03-06.adoc
Labels: trivial, V2025

#641 Clarify cross-cutting concerns vs. cross-cutting concepts
  docs/04-documentation/LG-04-07.adoc
Labels: enhancement, V2025

#649 648 lg 03 10 differentiate between cross cutting concerns and cross cutting concepts
  documentation/decisions/009-crosscutting-concerns-and-concepts.md
Labels: V2025, documentation

#653 #650-META decision on how the FLWG will decide
  documentation/decisions/010-how-we-decide.md
Labels: V2025, documentation

#654 #597 (hopefully) concludes the lengthy discussion on quality requirem…
  docs/02-requirements/LG-02-04.adoc
  documentation/decisions/008-specify-quality-requirements.md
Labels: learning content, enhancement, V2025, examination

#658 fixed this bug: "Expect Errors" and "SOLID" are still INCLUDED in cur…
  documentation/Mapping-2023-2025-draft.drawio
  documentation/Mapping-2023-2025-draft.drawio.png
Labels: bug, V2025

#659 another try with #564: This time on a fresh branch
  docs/03-design/LG-03-07.adoc
Labels: duplicate, in progress, learning content, enhancement, V2025

#663 #662 add three more book-references
  docs/09-references/00-references.adoc
Labels: V2025, documentation, minor

#661 LG 01-06 add data, not just data models
  docs/01-basics/LG-01-06.adoc
Labels: learning content, enhancement, V2025

#665 ADR on socio technical systems and re-introduction of LG on long term consequences, see Issue #657
  docs/01-basics/00-basic-concepts.adoc
  docs/01-basics/LG-01-03.adoc
  docs/01-basics/LG-01-04.adoc
  docs/01-basics/LG-01-05.adoc
  docs/01-basics/LG-01-06.adoc
  docs/01-basics/LG-01-07.adoc
  docs/09-references/00-references.adoc
  documentation/Mapping-2023-2025-draft.drawio
  documentation/Mapping-2023-2025-draft.drawio.png
  documentation/decisions/011-socio-technical-system-out-of-scope.md
Labels: learning content, V2025, minor

#668 fixed wrong title of LG 1-7 (data and data models)
  documentation/Mapping-2023-2025-draft.drawio
  documentation/Mapping-2023-2025-draft.drawio.png
Labels: bug, V2025

#664 LG-02-02 clarified intro after LENGTHY discussion in #543
  docs/02-requirements/LG-02-02.adoc
  docs/09-references/00-references.adoc
Labels: in progress, learning content, enhancement, V2025, minor
