Repository isaqb-org/curriculum-foundation, pull requests merged in 2025-03, with the labels that each got.

#732 #730 moved remote procedure call (RPC) from Design Patterns (LG 03.08…
  docs/03-design/LG-03-08.adoc
  docs/03-design/LG-03-09.adoc
Labels: bug

#740 LG-3-09 removed the distinction between architecture and design patte…
  docs/03-design/LG-03-08.adoc
  docs/03-design/LG-03-09.adoc
Labels: enhancement, V2025

#744 fixed #743, wording in description of R1
  docs/00-preamble/05-exam-relevance-levels.adoc
Labels: documentation

#745 the link to the release-process image was broken
  README.adoc
Labels: bug

#748 Handle References to Old LGs Consistently
  docs/01-basics/LG-01-05.adoc
  docs/02-requirements/LG-02-04.adoc
  docs/02-requirements/LG-02-05.adoc
  docs/03-design/LG-03-02.adoc
  docs/03-design/LG-03-03.adoc
  docs/03-design/LG-03-04.adoc
  docs/03-design/LG-03-05.adoc
  docs/03-design/LG-03-06.adoc
  docs/03-design/LG-03-07.adoc
  docs/03-design/LG-03-08.adoc
  docs/03-design/LG-03-09.adoc
  docs/03-design/LG-03-10.adoc
  docs/04-documentation/LG-04-01.adoc
  docs/04-documentation/LG-04-02.adoc
  docs/04-documentation/LG-04-03.adoc
  docs/04-documentation/LG-04-05.adoc
  docs/04-documentation/LG-04-06.adoc
  docs/04-documentation/LG-04-08.adoc
  docs/04-documentation/LG-04-09.adoc
  docs/06-examples/LG-06-01.adoc
  docs/06-examples/LG-06-02.adoc
Labels: bug

#751 fix #718, highlighting that prerequisites might be checked.
  docs/00-preamble/03-prerequisites.adoc
Labels: enhancement, documentation

#753 #752 fixed missing links in readme
  README.adoc
Labels: bug, V2025, documentation
